create table Users(
	user_id int primary key generated by default as identity,
	user_tg_id varchar(10) not null unique, 
	user_name varchar(30) not null,
	user_tg_username varchar(30) unique,
	user_phone varchar(20) not null unique
);

create table Applications(
	app_id int primary key generated by default as identity,
	app_date date not null,
	app_type varchar(150) not null,
	app_status varchar(12) not null default 'NEW',
	app_price varchar(10) default null,
	app_comment varchar(255) default null,
	app_user_id int,
	foreign key (app_user_id) references Users(user_id) on update cascade
);

create table helps(
	help_id int primary key generated by default as identity,
	help_text TEXT not null,
	help_status varchar(12) not null default 'WAITING',
	help_uid int not null,
	foreign key (help_uid) references Users(user_id) on update cascade
);
