[user_msg]
msg_hello = "<strong>Привет! Это ROLOC-бот</strong> 🤖\n\n▫️ <ins>ROLOC</ins> – это современный дизайн-сервис. Здесь можно заказать дизайн для бизнеса.\n\n©️Логотип\n📱Афиши | Посты для соц.сетей\n🪧Баннеры\n🧾Меню\n🪪Визитки\n🔖Стикеры\n🧧Сертификаты\n\nКаждый 5-ый дизайн <strong>БЕСПЛАТНО!</strong>\n* <ins>распространяется не на все услуги дизайна</ins>"

msg_hello_exists = "<strong>Привет! Это ROLOC-бот 🤖\nРады видеть Вас снова!</strong>\n\n▫️<ins>ROLOC</ins> – это современный дизайн-сервис. Здесь можно заказать дизайн для бизнеса.\n\n©️Логотип\n📱Афиши | Посты для соц.сетей\n🪧Баннеры\n🧾Меню\n🪪Визитки\n🔖Стикеры\n🧧Сертификаты\n\nКаждый 5-ый дизайн <strong>БЕСПЛАТНО!</strong>\n* <ins>распространяется не на все услуги дизайна</ins>"
msg_uname = "👤 Как Вас зовут?"
msg_uprbl = '📝 Опишите Вашу проблему'
msg_numbr = "📞 Отправьте номер телефона"
msg_contc = "📱 Отправьте Ваши контактные данные"
msg_commt = "📱 Где Вам будет удобнее связаться?\n\n▫️ Можете отправить несколько способов связи одним сообщением"
msg_quest = "Выберите несколько опций из списка услуг"
msg_userhelps_noexs = "🙅 У Вас пока что отсуствуют заявки на помощь"
msg_userappls_noexs = "🙅 У Вас пока что отсуствуют обращения"
msg_userappls_failed = "При создании заявки что-то пошло не так..."
msg_userhelps_failed = "При создании обращения что-то пошло не так..."
msg_media = "Медиафайлы на данном этапе не принимаются"
msg_procd = "<strong>🕔 ЗАЯВКА ОБРАБОТАНА!</strong>\nС Вами свяжутся в течении некоторого времени"
msg_faild = "<strong>Что-то пошло не так...</strong>\n\n<em>Попробуйте заполнить заявку заново</em>"
msg_about ="Вы можете узнать подробнее о нас в наших соц.cетях или связаться с нами для сотрудничества\n\n ✉️ Наш email: roloc.sup@yandex.ru"
msg_servs = "<strong>🔝 Давайте вместе сделаем Ваш бизнес лучше!</strong>\n\n<em>Выберете одно из направлений, в котором Вам требуются услуги дизайнера</em>\n\nИли выберите <strong>«Комплекс услуг»</strong>"
msg_wishs = "<strong>🌠 Напишите Ваши пожелания</strong>\n\n<em>▫️ Любая полезная для нас информация:</em>\n- Уточнения по прикрепленным файлам\n- Корпоративные цвета и шрифты (при наличии)\n- И др.\n\n<u>Или просто отправьте '-'</u>"
msg_files = "<strong>❕По желанию</strong>:\n\n📷 Прикрепите 1 или несколько фотографий\n🎙 Отправьте голосовое сообщение или кружок с описанием задачи\n📁Отправьте файл, в котором описана задача\n\nИли нажмите на кнопку 'Завершить'"
msg_price = "💵 Что Вы думаете о цене?\n\n <em>От цены будет зависит опыт дизайнера, который займется вашим проектом.</e>"
msg_speed = "🚀 Что Вы думаете о скорости?\n\n<em>От скорости исполнения может меняться цена.</em>"
msg_numsd = "📘 Укажите количество сторон печати"
msg_produ = "⚒️ Нужно ли изготовление?"
msg_sizze = "📐 Укажите размер баннера"
msg_numpg = "📃 Укажите количество страниц"
msg_brief = "📡 Откуда Вы о нас узнали?"
msg_adv = "Интересуешься развитием бизнеса?\nМы поможем сделать твой бизнес более узнаваемым и привлекательным. Дарим скидку 10% на первый заказ по промокоду «БИЗНЕС10»"
command_start = "Начало работы"
command_about = "Подробнее о нас"
command_helps = "Мне нужна помощь"

[user_kb]
usermenu1 = 'Создать дизайн! 🧩'
usermenu_w = 'Веб-приложение 📱'
usermenu2 = 'Подробнее о нас 🌐'
usermenu3 = 'Мне нужна помощь 🆘'
usermenu4 = 'Мои заявки 📨 '
usermenu5 = 'Мои обращения 📝 '
usermenu6 = "50 советов предпринимателям 📕"
usermenu7 = "Отзывы 🗣"

link_otziv = "https://yandex.ru/profile/224240886731"
link_vk = 'https://vk.com/roloc.design'
link_tg = 'https://t.me/roloc_design'
link_st = 'https://roloc.ru/'
link_wa = 'https://t.me/RolocBot/ROLOC'

serv_1 = "Логотип"
serv_2 = "Логобук / Брендбук"
serv_3 = "Дизайн упаковки"
serv_4 = "Визитка"
serv_5 = "Баннер"
serv_6 = "Журнал / Меню"
serv_7 = "Открытка / Сертификат"
serv_8 = "Брошюра / Листовка"
serv_9 = "3D-модель"
serv_10 = "Комплекс услуг"

oneside = "Односторонняя"
twoside = "Двусторонняя"

price_1 = "Хочу сэкономить"
price_2 = "Средняя цена"
price_3 = "Готов заплатить"

speed_1 = "Готов подождать"
speed_2 = "Средняя скорость"
speed_3 = "Как можно быстрее"

brief_1 = "Реклама в интернете"
brief_2 = "Рекламный баннер"
brief_3 = "Рекомендация"
brief_4 = "Из соц.сетей"

finish = "Завершить"
approve = "Подтвердить"


[admin_msg]
msg_hello = "<strong>Привет, админ! 🚀</strong>\n▫️Выбери нужную тебе опцию:"
msg_umenu = "<strong>Ты перешел в меню пользователя! 🚀</strong>\n▫️Выбери нужную тебе опцию:"
msg_dberr = "🔌⚠️ <strong>Произошла проблема с подключением к базе данных!</strong>\n<i>Заявка пользователя не сохранена в базу, но отправлена тебе</i>"
msg_error = "🔌❌ <strong>Ошибка подключения к базе данных</strong>"
msg_dberr_help = "🔌❌ <strong>Ошибка подключения к базе данных</strong>"
msg_help_error =  "Ошибка при нажатии на помощь"
msg_main_menu = "Выбери опцию"
msg_apps_menu = "📥 Меню заявок"
msg_help_menu = "🆘 Меню помощей"

# for no exists
msg_noexs_number = "🙅 <strong>Заявки с таким номером не существует</strong>"
msg_noexs_status = "🙅 <strong>Заявок с таким статусом не существует</strong>"
msg_noexs_srvice = "🙅 <strong>Заявок с таким типом нет</strong>"
msg_noexs_sldate = "🙅 <strong>Заявок на эту дату нет</strong>"
msg_noexs_uphone = "🙅 <strong>Заявок на данный номер нет</strong>"
msg_noexs_help = "🙅 <strong>По такому ID нет обращений</strong>"
msg_allhelp_noexs = "✅ <strong>Пока что просьб о помощи не поступало</strong>"
help_noexs_status = "🙅 <strong>Обращений с таким статусом не существует</strong>"
help_noexs_uphone = "🙅 <strong>Обращений по данному номеру не поступало</strong>"

# for search handler
msg_search_option = "<strong>⚙️ Выберите опцию поиска</strong>"
msg_search_number = "<strong>🆔 Отпрвьте номер заявки</strong>"
msg_search_srvice = "<strong>💻 Выберите услугу</strong>"
msg_search_chdate = "<strong>📆 Напишите нужную дату в формате:</strong> <u>Год.Месяц.День</u>"
msg_search_status = "<strong>✅ Выберите необходимый статус заявки</strong>"
msg_search_uphone = "<strong>📞 Отправьте номер телефона пользователя</strong>"

# for change handler
msg_change_param = "⚙️ <strong>Выберите параметр изменения</strong>"
msg_change_price = "💰 <strong>Отправьте стомость заявки</strong>"
msg_change_commt = "💬 <strong>Отправьте комментарий к заявке</strong>"

msg_search_helpid = "🆔 Отправьте ID помощи"
msg_helps_select_param = "Выбери опцию поиска"

msg_change_failed_commt = "😣 <strong>Не удалось обновить коммент</strong>\n\n<em>Попробуйте обновить коммент немного позже</em>"
msg_change_failed_price = "😣 <strong>Не удалось обновить цену</strong>\n\n<em>Попробуйте обновить цену немного позже</em>"
msg_change_failed_stats = "😣 <strong>Не удалось обновить статус</strong>\n\n<em>Попробуйте обновить статус немного позже...</em>"

msg_change_success_commt = "<strong>Комментарий к заявке успешно добавлен!</strong> 💬✅"
msg_change_success_price = "<strong>Цена заявки успешно обновлена!</strong> 💰✅"
msg_change_success_stats = "<strong>Статус заявки успешно обновлен!</strong> ♻️✅"
msg_help_change_success = "Статус помощи успешно изменен"

[admin_kb]
adm_search = "Поиск заявки                                    🔎"
adm_change = "Изменение заявки                          🔄"
adm_switch_user_menu = "Перейти в меню пользователя   📲"

adm_appls = "Заявки 📥"
adm_helps = "Помощи 🆘"

admhelps_search = "Поиск 🔎"
admhelps_change = "Изменить ♻️"

helpstatus_1 = "В ожидании 🕔"
helpstatus_2 = "Обработана ✅"

hsearch_all = "Все помощи                                    🆘"
hsearch_hid = "Поиск по ID                                     🆔"
hsearch_sts = "Поиск по cтатусу                          ♻️"
hsearch_uph = "Поиск по номеру телефона       📞"

search_id = "Поиск по ID                                       🆔"
search_sr = "Поиск по услуге                              💻"
search_dt = "Поиск по дате                                  📆"
search_st = "Поиск по cтатусу                            ♻️"
search_pn = "Поиск по номеру телефона         📞"

change_stus = "Изменить статус заявки ♻️"
change_prce = "Изменить стоимость заявки 💰"
change_comm = "Изменить комментарий к заявке 💬"

appstatus_1 = "Новая 🆕"
appstatus_2 = "В обработке 🕔"
appstatus_3 = "Cоставление ТЗ 📘"
appstatus_4 = "Ожидание оплаты 💳"
appstatus_5 = "Правки 📝"
appstatus_6 = "Завершена ❌"


[common_kb]
yes = "Да"
no = "Нет"
back = "Перейти в меню"
